; Generated by ~/.emacs.d/tools/omit.py
; This file should be commited to the repository.
(provide 'omit)

(add-hook 'dired-mode-hook 'dired-omit-mode)
(setq dired-omit-files "^\\.\\([^\\.ge]\\|g[^i]\\|gi[^t]\\|e[^m]\\|em[^a]\\|ema[^c]\\|emac[^s]\\|$\\)")
